# @package _group_
env: "Bixler-v0"
term_fn: perching_long
env_cfg:
  _target_: "torchperch.gym-bixler.gym_bixler.envs.bixler_env.BixlerEnv"
  
num_steps: 100000
epoch_length: 250
num_elites: 5
patience: 25
model_lr: 4e-4
model_wd: 3e-5
model_batch_size: 256
validation_ratio: 0.0
freq_train_model: 250
no_delta_list: [ 0 ]
effective_model_rollouts_per_step: 400
rollout_schedule: [1, 15, 1, 1]
num_sac_updates_per_step: 20
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1

sac_gamma: 0.99
sac_tau: 0.005
sac_alpha: 0.2
sac_policy: "Gaussian"
sac_target_update_interval: 1
sac_automatic_entropy_tuning: true
sac_target_entropy: -0.05
sac_hidden_size: 512
sac_lr: 0.0001
sac_batch_size: 256