# @package _group_
env: "ArduPilot-v0"
term_fn: no_termination
env_cfg:
  _target_: "ardupilot-gym.ardupilot_gym.envs.sitl.ArduPlaneSITLEnv"
  
num_steps: 1000
epoch_length: 250
num_elites: 5
patience: 10
model_lr: 0.0003
model_wd: 0.00005
model_batch_size: 256
validation_ratio: 0.2
freq_train_model: 50
effective_model_rollouts_per_step: 400
rollout_schedule: [1, 15, 1, 1]
num_sac_updates_per_step: 10
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1

sac_gamma: 0.99
sac_tau: 0.005
sac_alpha: 0.2
sac_policy: "Gaussian"
sac_target_update_interval: 4
sac_automatic_entropy_tuning: false
sac_target_entropy: -1
sac_hidden_size: 512
sac_lr: 0.0001
sac_batch_size: 256