# @package _group_
env: "ArduPilot-v0"
term_fn: no_termination
env_cfg:
  _target_: "ardupilot-gym.ardupilot_gym.envs.sitl.ArduPlaneSITLEnv"
  
learned_rewards: True
num_steps: 10000
trial_length: 100

action_optimizer: mppi


num_elites: 5
model_lr: 2e-4
model_wd: 3e-5
model_batch_size: 32
validation_ratio: 0.0
freq_train_model: 2
patience: 25
num_epochs_train_model: 25

# planning_horizon: 5
# cem_num_iters: 5
# cem_elite_ratio: 0.1
# cem_population_size: 350
# cem_alpha: 0.1
# cem_clipped_normal: false

# planning_horizon: 10
# cem_num_iters: 5
# cem_elite_ratio: 0.1
# cem_population_size: 200
# cem_population_decay_factor: 1.3
# cem_colored_noise_exponent: 2
# cem_keep_elite_frac: 0.3
# cem_alpha: 0.1

planning_horizon: 5
mppi_num_iters: 5
mppi_population_size: 350
mppi_gamma: 0.9
mppi_sigma: 1.0
mppi_beta: 0.9