# @package _group_
env: "RealFlight-v0"
term_fn: realflight_hang
env_cfg:
  _target_: "realflight_gym.gym-realflight.gym_realflight.envs.realflight_env.RealFlightEnv"
  
learned_rewards: True
num_steps: 10000
trial_length: 1000

num_elites: 5
model_lr: 4e-4
model_wd: 3e-5
model_batch_size: 256
validation_ratio: 0.0
no_delta_list: [ 0 ]
freq_train_model: 250
patience: 25
num_epochs_train_model: 25

planning_horizon: 30
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 350
cem_alpha: 0.1
cem_clipped_normal: false